### ISSUE TITLE
Help text could be in code rather than the db

### ISSUE THREAD

**Issue by andybak** [quiqueporta/django-admin-dialog#1]
Happy to make produce a pull request for this but wanted to get your thoughts.

I'd love to use this with one modification - I would want to define my help text in admin.py rather than having it db editable - this is simpler for us and means that changes are easier to deploy and manage.

This could be an option set via a setting.

(That would also remove the need for django-redactoreditor) 

Is it worth incorporating this or is it such a major change that we'd be better off forking?

**Comment by quiqueporta** [comment]
Hi Andy!
Thanks for your feedback :+1:
This package is more focused for my customers who have other customers and they need change help texts sometimes.
If i define the help texts in admin.py i should do a deploy whenever they wanted to make a small change in the help texts or add a new help text to another form field.
Perhaps this is not your goal :confused:.
I think for your purposes would be better to make a fork.
And about the django-redactor, i need this dependency because my customers sometimes need to insert a embed video :sweat: or a table.
Thanks again for your feedback :wink:
